import {Calc} from "./calculatorTask.js"
import { menu,multiplyNumeric } from "./objectValuesX2Task.js"
import { fedorenka } from "./taskFedorenka.js"
import { backRecursion,createNewRecursion } from "./createRecursionTask.js"
import { user } from "./skillsObjectTask.js"
import { createAuto } from "./autobaseTask.js"
import { foundLettersNum } from "./alphabetNumberTask.js"
import { bitReverse } from "./bitReturnTask.js"
import { createPhoneNum } from "./changeNumbersFormatTask.js"
import { sortTrolles } from "./deleteSymbolsTask.js"
import { findOutlierValue } from "./findOutlierValueTask.js"
import { createNum } from "./numbersInOneCalc.js"
import { newStr } from "./reverseStringTask.js"
import { sortDoublesAndDelete } from "./serchAndDeleteTask.js"
import { streetGamesScore } from "./streetGamesTask.js"
import { checkUsers } from "./stringConfiguratorTask.js"
import { nameInStr } from "./ nameInStringTask.js"
import { testWawe1} from "./testWaweTask.js"
import { diagramCreator } from "./graphicCreatorTask.js"
